### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by varunagrawal** [b4b4r07/emoji-cli#10]
I installed the plugin as mentioned on the README.md and added it to my plugins list. However when I type:

    echo "Hey there! :smile:"

It simply prints `Hey there! :smile:`.

**Comment by Rawnly** [comment]
This plugin doesn't shows emoji in your terminal, but only suggest them on <kbd>ctrl+s</kbd>.

To show them you need to use something like [emojify](https://github.com/mrowa44/emojify) as shown in the readme.
