### ISSUE TITLE
Support search by all aliases

### ISSUE THREAD

**Issue by krokofant** [b4b4r07/emoji-cli#13]
Currently only the first alias seems to be matched against

_Sadly my shellscript-foo is horrible so I don't know how to fix it myself_

```
:hankey:
:poop:
:shit:
```

**Comment by b4b4r07** [comment]
Thank you.

We have to update [this dict file (json)](https://github.com/b4b4r07/emoji-cli/blob/master/dict/emoji.json) and it's so steady work.

**Comment by krokofant** [comment]
@b4b4r07 I looked over that file and saw that the :hankey: example already has it's up to date aliases defined:
```
"aliases": [
            "hankey",
            "poop",
            "shit"
        ]
```

So it seems to me there is something going on with the script.

**Comment by babarot** [comment]
I don't have time to support this, so closing. But I'm waiting contributors
