### ISSUE TITLE
LICENCE link is broken

### ISSUE THREAD

**Issue by WhyNotHugo** [b4b4r07/emoji-cli#22]
The link to the LICENCE is broken: https://b4b4r07.mit-license.org/

The licence is fetched to generate a [package for ArchLinux](https://aur.archlinux.org/packages/emoji-cli/) (packages must include a licence, after all).

Would you mind just including a file with it in the repo? :)

Thanks!

**Comment by marciska** [comment]
It works for me. Seems like it has been already fixed.

Can be closed I guess.

**Comment by babarot** [comment]
It works now.
